cart/urls.py
from django.urls import path
from cart import views

app_name = "cart"

urlpatterns = [
    path('', views.cart_summary, name="cart_summary"),
    path('add/', views.cart_add, name="cart_add"),
    path('delete/', views.cart_delete, name="cart_delete"),
    path('update/', views.cart_update, name="cart_update"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.products_all, name='products_all'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

cart/models.py
from django.db import models

# Create your models here.

store/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default="images/MM.png")
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title

cart/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from cart.cart import Cart
from store.models import Product

# Create your views here.
def cart_summary(request):
    cart = Cart(request)
    return render(request, 'store/cart/summary.html', {'cart' : cart})

def cart_add(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)# This line explained below
        #try:
        #   product = Product.objects.get(id = product_id)
        #except:
        #   raise Http404
        cart.add(product=product, qty=product_qty)
        cartqty = cart.__len__()
        response = JsonResponse({'qty' : cartqty})
        return response
    
def cart_delete(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        cart.delete(product = product_id)
        cart_total = cart.get_total_price()
        cartqty = cart.__len__()
        response = JsonResponse({'qty' : cartqty, 'subtotal' : cart_total})
        return response

def cart_update(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        #print(product_id)
        #print(product_qty)
        cart.update(product = product_id, qty = product_qty)
        cartqty = cart.__len__()
        cart_total = cart.get_total_price()
        #print(cart_total)

        response = JsonResponse({'qty' : cartqty, 'subtotal' : cart_total})
        return response

store/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category, Product


def products_all(request):
    products = Product.products.all()
    return render(request, 'store/home.html', {'products': products})


def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/products/category.html', {'category': category, 'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/products/single.html', {'product': product})

templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}SoShaTvStore{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">SoShaTvStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <!--<li class="nav-item active">
                            <a class="nav-link" aria-current="page" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>-->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Sections
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url "store:products_all" %}">All</a></li>
                                {% for c in categories %}
                                <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                                    <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                    <!--<form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>-->
                    <a type="button" role="button" href="{% url 'cart:cart_summary' %}" class="btn btn-outline-secondary">
                        {% with total_qty=cart|length %}
                        <div id="cart-qty" class="d-inline-flex">
                            {% if total_qty > 0 %}
                                {{total_qty}}
                            {% else %}
                                0
                            {% endif %}
                        </div>
                        {% endwith %}
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart4" viewBox="0 0 16 16">
                            <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
                          </svg>
                          Cart
                    </a>
                </div>
            </div>
        </nav>
    </header>
    <div id="content">{% block content %} {% endblock %}</div>
</body>
</html>

templates/store/cart/summary.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}
    Cart Summary
{% endblock %}
{% block content %}
    <main class="pt-5">
        <div class="container">
            <h1 class="h5">
                Shopping Cart
            </h1>
            {% for item in cart %}
                {% with product=item.product %}
                    <div data-index="{{product.id}}" class="row mb-4 border product-item">
                        <div class="col-md-3 col-lg-2 order-md-first bg-light">
                            <img class="img-fluid mx-auto d-block" width="120px" alt="Responsive image" src="{{ product.image.url }}">
                        </div>
                        <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
                            <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-reset"><h1 class="h5 pt-2">{{ product.title }}</h1></a>
                            <div class="border">
                                <div class="col border-bottom">
                                    <div class="row p-3">
                                        <div class="col-6">Price</div>
                                        <div class="col-6 text-end"><span class="h6 fw-bold">£{{ product.price }}</span></div>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="row p-3">
                                        <div class="col-12">
                                            <label for="select">Quantity</label>
                                            <select id="select{{product.id}}">
                                                <option selected>
                                                    {{item.qty}}
                                                </option>
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3">3</option>
                                                <option value="4">4</option>
                                            </select>
            
                                        </div>
                                        <div class="col-6 text-end">
                                            <button type="button" id="update_cart" data-index="{{product.id}}" class="btn btn-outline-secondary btn-sm update_cart">
                                                Update
                                            </button>
                                            <button type="button" id="delete_from_cart" data-index="{{product.id}}" class="btn btn-outline-secondary btn-sm delete_from_cart">
                                                Delete
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endwith %}
            {% endfor %}
            <div class="col-12 text-end">
                <div class="h6 fw-bold">
                    SubTotal: £<div id="subtotal" class="d-inline-flex">{{cart.get_total_price}}</div>
                </div>
            </div>
        </div>
    </main>

    <script>
        //Delete
        $(document).on('click', '.delete_from_cart', function(e){
            e.preventDefault();
            let prodid = $(this).data('index');
            $.ajax({
                type : "POST",
                url : "{% url 'cart:cart_delete' %}",
                data : {
                    productid : $(this).data('index'),
                    csrfmiddlewaretoken : "{{ csrf_token }}",
                    action : 'post',
                },
                success : function(json){
                    //console.log(prodid)
                    $('.product-item[data-index="'+ prodid + '"]').remove();
                    document.getElementById("subtotal").innerHTML = json.subtotal
                    document.getElementById("cart-qty").innerHTML = json.qty
                },
                error : function(xhr, errmsg, err){}
            });
        })
    </script>

    <script>
    //Update
        $(document).on('click', '.update_cart', function(e){
            e.preventDefault();
            let prodid = $(this).data('index');
            $.ajax({
                type : "POST",
                url : "{% url 'cart:cart_update' %}",
                data : {
                    productid : $(this).data('index'),
                    productqty : $('#select' + prodid + ' option:selected').text(),
                    csrfmiddlewaretoken : "{{ csrf_token }}",
                    action : 'post',
                },
                success : function(json){
                    //console.log(prodid)
                    //$('.product-item[data-index="'+ prodid + '"]').remove();
                    document.getElementById("cart-qty").innerHTML = json.qty
                    document.getElementById("subtotal").innerHTML = json.subtotal
                },
                error : function(xhr, errmsg, err){}
            });
        })
    </script>
{% endblock %}

templates/store/home.html
{% extends "./base.html" %}
{% load static %}
{% block title %}SoShaTvStore{% endblock %}
{% block content %}


<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-1">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="h1 fw-bold">Buy, Sell, Search, Window Shop</h1>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator,
          etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        <p>
          <a href="#" class="btn btn-primary my-2">Sign Up</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">All Sections</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
            <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">{{product.description}}</small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}

templates/store/products/category.html
{% extends "../base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}


<main>
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">{{category.name|title}}</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
          <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">

            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">{{product.description}}</small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}

templates/store/products/single.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ product.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product.title }}</h1>
                <p><span class="lead">{{ product.author }}</span> (Author)</p>
                <p>{{ product.description|slice:":355" }}...</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Price</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">£{{ product.price }}</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select">Qty</label>
                                <select id="select">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                </select>

                            </div>
                            <div class="col-6 text-end">
                                <button id="update_cart" value="{{product.id}}" type="button" class="btn btn-secondary btn-sm">
                                    Add to cart
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

</div>

<script>
    $(document).on('click', '#update_cart', function(e){
        e.preventDefault();
        $.ajax({
            type : "POST",
            url : "{% url 'cart:cart_add' %}",
            data : {
                productid : $('#update_cart').val(),
                productqty : $("#select option:selected").text(),
                csrfmiddlewaretoken : "{{ csrf_token }}",
                action : 'post',
            },
            success : function(json){
                document.getElementById("cart-qty").innerHTML = json.qty
            },
            error : function(xhr, errmsg, err){}
        });
    })
</script>

{% endblock %}